### ISSUE TITLE
Initial values

### ISSUE THREAD

**Issue by zvictor** [okonet/react-container-dimensions#1]
Thank you for this very handy project! I have just made a PR to add it to Recharts (http://recharts.org), but there is a minor thing that makes them sort of incompatible.

React-container-dimensions is always sending its initial state (width and height set to zero) to the children components on the first render, and therefore Recharts prints multiple warns saying that it can't render the charts in these conditions.

Can we send others values, other than zeros, to the children? What about having a third parameter `hasInitiated`, or send `null` as first values?

Link to the PR: recharts/recharts#105

**Comment by okonet** [comment]
Hey! Yeah, that's an issue I'm having with SSR as well. Not sure how to solve it though in a compatible manner. I was thinking of `defaultWidth` and `defaultHeight` as props for this purpose. `null` will complicate underlying component's logic IMO.

**Comment by okonet** [comment]
Another idea was to set them to `100%` initially like you did in the PR (https://github.com/recharts/recharts/pull/105/files#diff-64e08d9691c7f3156ef1dfd43b7c94e5R65)

**Comment by zvictor** [comment]
I think `100%` would not work well for Recharts, as it needs absolute values.

Would it be possible to have it like below?
```jsx
        <ContainerDimensions>
            { ({ width, height, hasLoaded }) => 
                hasLoaded ?
                    <svg width={width} height={height}>
                        {/* SVG contents */}
                    </svg>
                :
                    null
            }
        </ContainerDimensions>
```

**Comment by okonet** [comment]
Well, my main motivation is server-side rendering and not the compatibility with Recharts since this is doable in the callback. But I'll keep it in mind when approaching this one. 

Thanks again. If you'd like you can create a PR. But please keep SSR in mind.

**Comment by zvictor** [comment]
Sorry, I couldn't understand what  you mean by ` since this is doable in the callback `. Could you clarify it?

I think it is wrong to send `{ width: 0, height: 0 }` in the first render because it is just conceptually wrong since the container does not have these dimensions. My understanding is that we should not be sending wrong data just because we don't have the actual data.

So, to be able to get the real data (the container size), we need to render something in first place. Rendering `null` and then executing `ReactDOM.findDOMNode(this).parentNode` would fail. But we can't render the `children` because we don't have the dimensions yet. It is a circular dependency!

Therefore, we have three options:

1. Render a placeholder element, get the container size, and only then render the actual `children`.
2. Use values other than zero to denote that the values have not being initiated yet. This way, `children` would be able to know that when `{ width: null, height: null }` it should wait for the next render.
3. As mentioned before, having an attribute `hasInitiated` that we pass to the `children` so it is then aware that we don't have the actual dimensions yet and we give the `children` the responsibility of dealing with it.

I am sending now a PR for the approach 1.

**Comment by okonet** [comment]
Thanks! I really like the first approach. It should solve all issues I hope. What I miss are tests. Could you please add them as well?

**Comment by zvictor** [comment]
thank you!
