### ISSUE TITLE
Fails with react-test-renderer

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [okonet/react-container-dimensions#11]
Is there a way to make `react-container-dimensions` work with `react-test-renderer`? I'm trying to write some snapshot tests with `jest-snapshot` and getting the following failure:

```
     Invariant Violation: getNodeFromInstance: Invalid argument.
      at invariant (node_modules/fbjs/lib/invariant.js:38:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:155:77)
      at Object.findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at ContainerDimensions.componentDidMount (node_modules/react-container-dimensions/lib/index.js:69:50)
      ...
```

If the two are not compatible, is there a recommended workaround?

**Comment by okonet** [comment]
I'm using enzyme to test this component: https://github.com/okonet/react-container-dimensions/blob/master/tests/index.js

It's hard to say why your test fails but, in general, this component requires DOM so I assume this is why it isn't working with snapshot testing. You should probably only test the component you're wrapping if you want to use snapshots.

**Comment by uhoh-itsmaciek** [comment]
Thanks for the info. Feel free to close this unless you want to support `react-test-renderer` out of the box at some point.
