### ISSUE TITLE
element-resize-detector not removed correctly on componentWillUnmount

### ISSUE THREAD

**Issue by ValentinH** [okonet/react-container-dimensions#12]
I'm using this library in a `react-router` application and I have issues when using several detectors in different routes. On the first route, resize events are sent but when I go on a new route, then the library don't send the dimensions anymore.

After a bit of investigations, I found that the `element-resize-detector` needs to be uninstall on `componentWillUnmount` since it is instantiated on each `componentDidMount`. (See https://github.com/wnr/element-resize-detector#uninstallelement).

[This block](https://github.com/okonet/react-container-dimensions/blob/master/src/index.js#L32-L34) should be replaced by:
```js
 componentWillUnmount() {
    this.elementResizeDetector.uninstall(this.parentNode)
}
```
Then, everything works properly in React Router...

Do you want me to submit a Pull Request for this?

**Comment by okonet** [comment]
Oh that would be great. I was sure that `removeListener` is enough. Please submit a PR and some tests.

**Comment by ValentinH** [comment]
I'm very new to React and have never written tests for it, what would you test then?

**Comment by okonet** [comment]
I would write a test that should check if the `this.elementResizeDetector` is properly uninitialized. Check out the existing tests and try it out. If you have question, please don't hesitate to reach out to me and I'll try to help!

**Comment by ValentinH** [comment]
How do you test that `this.elementResizeDetector` is properly uninitialized?
I have try to simulate my issue in tests by mounting/unmounting twice, but I couldn't break it...

**Comment by ValentinH** [comment]
Actually, I tried to duplicate [this test](https://github.com/okonet/react-container-dimensions/blob/master/tests/index.js#L52-L69) and I found out it was broken.

Indeed, if you remove the 2 `.css()` calls, the test still passes which is wrong.

I found this because I was actually surprised that the "calls onResize on mount" passed while I was seeing the `onResize` callback called twice on mount in my application. Indeed, [this code](https://github.com/wnr/element-resize-detector/blob/master/src/element-resize-detector.js#L176-L178) shows that the `element-resize-detector` already calls the listener on add by default.

**Comment by okonet** [comment]
@ValentinH can you fix the test?

**Comment by ValentinH** [comment]
Yes I can. Just need to see what should be the correct behavior. 3 solutions:
1. we don't change the current behavior, that means that `onResize()` is called twice on load.
2. we instantiate the `elementResizeDetector` with the ̀callOnAdd: false` option and we keep calling `this.onResize()` on `mount`.
3. we remove the `this.onResize()` call on `mount` and let the `elementResizeDetector` do it.

I prefer solution number 2 instead of 3 because we know when it's called (easier to test) while with solution 3 we need to use `setTimeout()` in test to ensure it's called.

**Comment by okonet** [comment]
It seems it's not possible to test with the jsDOM so I've removed the test completely.

**Comment by ValentinH** [comment]
OK, but still the current behavior is a bit broken because `onResize` is called twice on load due to what I explain above. Do you think I should fix this? If yes, which solution do you prefer?

**Comment by okonet** [comment]
Oh I didn't know there is such option :) Option 2 would be great! I'll revert my commit with the test removal then.

**Comment by okonet** [comment]
@ValentinH there is #9 FYI

**Comment by ValentinH** [comment]
Indeed, you are right, this is exactly how I modified the test to understand the issue :)
