### ISSUE TITLE
React router props not passed to wrapped component

### ISSUE THREAD

**Issue by ValentinH** [okonet/react-container-dimensions#16]
I'm rendering a component in a react router route and when I wrap this component with `ContainerDimensions`, the props that are normally passed via the props by react router don't reached my component. Do you think it would be possible for `ContainerDimensions` to pass all the props it receives to its children?

Otherwise, have you ever deal with `ContainerDimensions` inside a Route?

Here's what I do:
```jsx
<Route path="/" component={MyComponent}/>
```

When I export `export default MyComponent` in my MyComponent.js file, the props contains this:
![image](https://cloud.githubusercontent.com/assets/2678610/23891893/b1bba5b8-0898-11e7-845c-0d9bd884c6b6.png)

While if I export this from my component:
```jsx
export default () => (
  <ContainerDimensions>
    <MyComponent/>
  </ContainerDimensions>
)
```
then I get these props:
![image](https://cloud.githubusercontent.com/assets/2678610/23891917/d192e180-0898-11e7-9ff4-e24c606189af.png)

Thus, I would like to merge this two objects.

**Comment by okonet** [comment]
Why not just make it explicit and pass router's props by yourself?

```js
export default (props) => (
  <ContainerDimensions>
    <MyComponent {...props} />
  </ContainerDimensions>
)
```

**Comment by ValentinH** [comment]
Because I'm new to React and did not know how to do that! 😄 Thanks 👍
